daily_parrot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'main.views.page_not_found'
handler500 = 'main.views.internal_server_error'
handler403 = 'main.views.permission_denied'
handler400 = 'main.views.bad_request'

main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from main import views

urlpatterns = [
    path('<slug:blog_post_slug>/thumbs/<str:action>/', views.thumbs, name='thumbs'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('add/', views.BlogPostCreateView.as_view(), name='blog_post_create'),
    path('@<str:username>/follow/', views.follow_profile, name='follow_profile'),
    path('@<str:username>/unfollow/', views.unfollow_profile, name='unfollow_profile'),
    path('topic/<slug:topic_slug>/unfollow/', views.unfollow_topic, name='unfollow_topic'),
    path('topic/<slug:topic_slug>/follow/', views.follow_topic, name='follow_topic'),
    path('@<str:username>/', views.ProfileDetailView.as_view(), name='profile'),
    path('@<str:username>/<slug:blog_post_slug>', views.BlogPostDetailView.as_view(), name='blog_post'),
    path('topic/<slug:topic_slug>/', views.TopicDetailView.as_view(), name='topic'),
    path('topics/', views.TopicsListView.as_view(), name='topics'),
    path('', views.HomePageView.as_view(), name='home'),
]

main/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from main import models

class BlogPostForm(forms.ModelForm):
       
    body = forms.CharField(widget=TinyMCE(attrs={'cols':80,'rows':30}))
    
    class Meta:
        model = models.BlogPost
        exclude = ['slug', 'author', 'thumbs_up', 'thumbs_down']
        
class ProfileForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    avatar = forms.ImageField()
    bio = forms.CharField()

main/views.py
from django.views.generic import ListView, DetailView, CreateView, FormView, TemplateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.db.models import Sum
from random import sample

from main import models, forms

class HomePageView(TemplateView):
    template_name = 'home.html'
    PER_PAGE = 20
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_authenticated:
            authors = models.Profile.objects.exclude(pk=self.request.user.profile.pk).\
                    annotate(rating=Sum('blog_posts__thumbs_up')).order_by('rating')
            following_posts = user.profile.get_following_posts()
            posts_list = models.BlogPost.objects.exclude(
                id__in=[p.pk for p in following_posts]).exclude(author=user.profile)
            posts_list = following_posts + list(posts_list)
        else:
            authors = models.Profile.objects.annotate(rating=Sum('blog_posts__thumbs_up')).order_by('rating')
            posts_list = models.BlogPost.objects.active()
        paginator = Paginator(posts_list, self.PER_PAGE)
        page = self.request.GET.get('page', 1)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        ctx['authors'] = authors[:3]
        ctx['posts'] = posts
        return ctx    

class TopicsListView(ListView):
    model = models.Classification
    context_object_name = 'classifications'
    template_name = 'topics.html'
    
class TopicDetailView(DetailView):
    template_name = 'topic.html'
    PER_PAGE = 20
    
    def get_object(self):
        obj = get_object_or_404(models.Topic, slug=self.kwargs['topic_slug'])
        return obj
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        topic_posts = self.object.blog_posts.all()
        paginator = Paginator(topic_posts, 30)
        page = self.request.GET.get('page', 1)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        ctx['posts'] = posts
        
        return ctx
    
class ProfileDetailView(DetailView):
    template_name = 'profile.html'
    PER_PAGE = 10
    
    def get_object(self):
        username = self.kwargs['username']
        user = get_object_or_404(get_user_model(), username=username)
        obj = get_object_or_404(models.Profile, user=user)
        return obj
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        posts_list = self.object.blog_posts.all()
        page = self.request.GET.get('page', 1)
        paginator = Paginator(posts_list, self.PER_PAGE)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        ctx['posts'] = posts
        if self.request.user.is_authenticated:
            is_following = self.request.user.profile.\
                is_following_profile(self.object)
            ctx['is_following'] = is_following
        return ctx
    
class BlogPostDetailView(DetailView):
    template_name = 'blog_post.html'
    
    def get_object(self):
        blog_post_slug = self.kwargs['blog_post_slug']
        obj = models.BlogPost.objects.active().get(slug=blog_post_slug)
        return obj
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        topic = self.object.topic
        try:
            suggestions = models.BlogPost.objects.topic_suggestions(topic, 3).\
                exclude(id=self.object.id)
            ctx['topic_suggestions'] = suggestions
        except AttributeError:
            topics = models.Topic.objects.exclude(id=topic.id).all()
            topics = sample(list(topics), 3)
            ctx['topics'] = topics
        if self.request.user.is_authenticated:
            is_following = self.request.user.profile.\
            is_following_profile(self.object.author)
            ctx['is_following'] = is_following
        return ctx

@login_required
def follow_topic(request, topic_slug):
    topic = get_object_or_404(
        models.Topic, slug=topic_slug
    )
    profile = request.user.profile
    profile.follow_topic(topic)
    return redirect(reverse('topic', args=[topic.slug]))

@login_required
def unfollow_topic(request, topic_slug):
    topic = get_object_or_404(
        models.Topic, slug=topic_slug
    )
    profile = request.user.profile
    profile.unfollow_topic(topic)
    return redirect(reverse('topic', args=[topic.slug]))

@login_required
def follow_profile(request, username):
    user = get_user_model().objects.get(username=username)
    profile = get_object_or_404(models.Profile, user=user)
    #actual following
    request.user.profile.follow_profile(profile)
    return redirect(reverse('profile', args=[username]))

@login_required
def unfollow_profile(request, username):
    user = get_user_model().objects.get(username=username)
    profile = get_object_or_404(models.Profile, user=user)
    #actual unfollowing
    request.user.profile.unfollow_profile(profile)
    return redirect(reverse('profile', args=[username]))

@login_required
def thumbs(request, blog_post_slug, action):
    post = models.BlogPost.objects.get(slug=blog_post_slug)
    if action == 'UP':
        post.thumbs_up += 1
    elif action == 'DOWN':
        post.thumbs_down += 1
    post.save()
    return redirect(post.get_absolute_url())
    
class BlogPostCreateView(LoginRequiredMixin, CreateView):
    form_class = forms.BlogPostForm
    template_name = 'blog_post_create.html'
    
    def dispatch(self, *args, **kwargs):
        if not self.request.user.profile.confirmed:
            messages.warning(self.request, 'confirm your email first before writing an article')
            return redirect('home')
        return super().dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        form.instance.slug = slugify(form.instance.title)
        form.instance.active = True
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        tags = models.Tag.objects.all()
        topics = models.Topic.objects.all()
        ctx['tags'] = tags
        ctx['topics'] = topics
        return ctx
    
class EditProfileView(LoginRequiredMixin, FormView):
    form_class = forms.ProfileForm
    template_name = 'edit_profile.html'
    
    def get_initial(self):
        init = super().get_initial()
        init['first_name'] = self.request.user.first_name
        init['last_name'] = self.request.user.last_name
        init['username'] = self.request.user.username
        init['email'] = self.request.user.email
        init['bio'] = self.request.user.profile.bio
        init['avatar'] = self.request.user.profile.avatar
        
        return init
    
    def form_valid(self, form):
        user_data = {
            'first_name': form.cleaned_data['first_name'],
            'last_name': form.cleaned_data['last_name'],
            'username': form.cleaned_data['username'],
            'email': form.cleaned_data['email'],
        }
        profile_data = {
            'bio': form.cleaned_data['bio'],
            'avatar': form.cleaned_data['avatar'],
        }
        
        for attr, value in user_data.items():
            setattr(self.request.user, attr, value)
            
        for attr, value in profile_data.items():
            setattr(self.request.user.profile, attr, value)
            
        self.request.user.save()
        self.request.user.profile.save()
        return self.get_success_url()
        
    def get_success_url(self):
        return redirect(reverse_lazy('profile',  args=[self.request.user.username]))
    
def page_not_found(request, exception):
    return render(request, 'error/404.html', status=404)

def internal_server_error(request):
    return render(request, 'error/500.html', status=500)

def permission_denied(request, exception):
    return render(request, 'error/403.html', status=403)

def bad_request(request, exception):
    return render(request, 'error/400.html', status=400)

templates/account_activation_sent.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Check your inbox <span class="fas fa-envelope"></span></h1>
        <p>Account activation email sent.</p>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Daily Parrot{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'images/parrot.svg' %}" type="image/x-icon">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!--Fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Lato&family=Merriweather:wght@300&display=swap" 
    rel="stylesheet">
    <!--Fontawesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.18.0/css/mdb.min.css" rel="stylesheet">
    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock styles %}
</head>
<body>
<!--Start of Navbar-->
<nav class="navbar navbar-expand-lg">
    <a class="navbar-brand text-dark" href="{% url 'home' %}">
        <img id='nav-logo' src="{% static 'images/parrot.svg' %}" alt="">
        <p class="navbar-brand" id='nav-brand'>Daily Parrot</p>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fas fa-bars"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mr-4 p-2">
        {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link nvl {% if request.path == '/' %}active{% endif %}" href="{% url 'home' %}">
              home
              <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link nvl" href="{% url 'topics' %}">topics</a>
          </li>
          <li class="nav-item">
            <a class="nav-link nvl" href="{% url 'blog_post_create' %}" tabindex="-1" aria-disabled="true">write</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fas fa-user-circle"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'profile' user.username %}">Profile</a>
              <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">logout</a>
            </div>
          </li>
        </ul>
      {% else %}
      <li class="nav-item my-auto mr-4">
        <a class="nav-link nvl" href="{% url 'topics' %}">topics</a>
      </li>
        <div class="p-2">
          <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
          <a href="{% url 'signup' %}" class="btn btn-secondary">Signup</a>
        </div>
      {% endif %}
    </div>
  </nav>
<!--End of navbar-->
<div class="container-fluid h-100">
    <br>
    {% for message in messages %}
      <div id="message" class="alert alert-{{ message.tags }} alert-dismissable fade show m-0 mx-auto" role="alert">
        {{ message }}
        <button class="close" role="button" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
    {% block content %}
    {% endblock content %}
</div>
<!--Jquery-->
<script src="{% static 'mdb/js/jquery.min.js' %}" ></script>
<!--Popper js-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.0/umd/popper.min.js"></script>
<!--Bootstrap JS-->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'mdb/js/mdb.js' %}">
</script>
<!--Fontawesome JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>
{% block scripts %}{% endblock scripts %}
</body>
</html>

templates/blog_post_create.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    {{ form.media }}
    <style>
        #submit-btn{
            width: 150px;
        }
    </style>
{% endblock styles %}

{% block scripts %}
<script>
    $(document).ready(function() {
        $('.mdb-select').materialSelect();
    });
</script>
{% endblock scripts %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h2 class="mb-0">Be our parrot ...</h2>
    <p class="text-muted mt-0">write</p>
    <div class="row">
        <div class="col-md-9 pl-10">
            <div class="mb-2">{{ form.body }}</div>
        </div>
        <div class="col-md-3 ml-auto">
            <div class="form-group">
                <input type="text" name="title" id="id_title" class="form-control mb-2 
                {% if form.title.errors %}is-invalid{% endif %}"
                placeholder="Title" required>
                {% if form.title.errors %}
                    {% for error in form.title.errors %}
                        <span class="invalid-feedback pb-1">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                <input type="text" name="tagline" id="id_tagline" class="form-control mb-2 
                {% if form.tagline.errors %}is-invalid{% endif %}"
                placeholder="Tagline" required>
                {% if form.tagline.errors %}
                    {% for error in form.tagline.errors %}
                        <span class="invalid-feedback pb-1">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                <select name="topic" required id="id_topic" class="custom-select mb-2 
                {% if form.topic.errors %}is-invalid{% endif %}">
                    <option value="" selected>Choose Topic</option>
                    {% for topic in topics %}
                        <option value="{{ topic.id }}">{{ topic.name }}</option>
                    {% endfor %}
                </select>
                {% if form.topic.errors %}
                    {% for error in form.topic.errors %}
                        <span class="invalid-feedback pb-1">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                <select name="tags" required id="id_tags" class="mdb-select mb-2 
                {% if form.first_name.errors %}is-invalid{% endif %}" multiple>
                    <option value="" disabled selected>Choose Tag</option>
                    {% for tag in tags %}
                        <option value="{{ tag.id }}">{{ tag.name }}</option>
                    {% endfor %}
                </select>
                {% if form.tags.errors %}
                    {% for error in form.tags.errors %}
                        <span class="invalid-feedback pb-1">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                <div class="input-group mb-2 {% if form.avatar.errors %}is-invalid{% endif %}">
                    <div class="input-group-prepend">
                        <div class="input-group-text">Upload</div>
                    </div>
                    <div class="custom-file">
                        <input type="file" name="banner" accept="image/*" required 
                        id="id_banner" class="custom-file-input">
                        <label for="id_banner" class="custom-file-label">Choose banner</label>
                    </div>
                </div>
                {% if form.avatar.errors %}
                    {% for error in form.avatar.errors %}
                        <span class="invalid-feedback pb-1">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                <div class="row">
                    <button type="submit" id="submit-btn" class="btn btn-outline-success 
                    btn-lg mx-auto">Post</button>
                    {{ form.errors }}
                </div>
            </div>
        </div>
    </div>
    
</form>
{% endblock content %}

templates/edit_profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block styles %}
<style>
    .container{
        width: 1000px;
    }
    .avatar{
        border-radius: 100px;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <h2>Edit Profile</h2><hr>
    <div class="row">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <p>Name</p>
                    <div class="row mb-2">
                        <div class="col-md-6 pr-2">
                            <input type="text" name="first_name" id="id_first_name" 
                            class="form-control {% if form.first_name.errors %}is-invalid{% endif %}"
                            placeholder="First Name" value="{{ form.first_name.value }}">
                            {% if form.first_name.errors %}
                            {% for error in form.first_name.errors %}
                                <span class="invalid-feedback pb-1">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-md-6 pl-2">
                            <input type="text" name="last_name" id="id_last_name" 
                            class="form-control {% if form.last_name.errors %}is-invalid{% endif %}"
                            placeholder="Last Name" value="{{ form.last_name.value }}">
                            {% if form.last_name.errors %}
                            {% for error in form.last_name.errors %}
                                <span class="invalid-feedback pb-1">{{ error }}</span>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <p>username</p>
                    <input type="text" name="username" id="id_username" 
                    class="form-control mb-2 {% if form.username.errors %}is-invalid{% endif %}"
                    placeholder="username" value="{{ form.username.value }}">
                    {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <span class="invalid-feedback pb-1">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                    <p>email</p>
                    <input type="email" name="email" id="id_email" 
                    class="form-control mb-2 {% if form.email.errors %}is-invalid{% endif %}"
                    placeholder="email address" value="{{ form.email.value }}">
                    {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <span class="invalid-feedback pb-1">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                    <p>bio</p>
                    <input type="text" name="bio" id="id_bio" 
                    class="form-control mb-2 {% if form.bio.errors %}is-invalid{% endif %}"
                    placeholder="bio" value="{{ form.bio.value|default_if_none:"" }}">
                    {% if form.bio.errors %}
                    {% for error in form.bio.errors %}
                        <span class="invalid-feedback pb-1">{{ error }}</span>
                    {% endfor %}   
                    {% endif %}               
                </div>
        </div>
        <div class="col-md-5">
            <div class="text-center mb-0">
                {% thumbnail user.profile.avatar "80x80" crop="center" as im %}
                    <img src="{{ im.url }}" alt="avatar" width="{{ im.width }}" height="{{ im.height }}" 
                    class="avatar mx-auto">
                {% endthumbnail %}
            </div>
            <br>
            <div class="input-group mb-2 {% if form.avatar.errors %}is-invalid{% endif %}">
                <div class="input-group-prepend">
                    <div class="input-group-text">Upload</div>
                </div>
                <div class="custom-file">
                    <input type="file" name="avatar" accept="image/*"
                    id="id_avatar" class="custom-file-input" value="{{ form.avatar.value }}">
                    <label for="id_avatar" class="custom-file-label">Change avatar</label>
                </div>
            </div>
            {% if form.avatar.errors %}
            {% for error in form.avatar.errors %}
                <span class="invalid-feedback pb-1">{{ error }}</span>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    
        <button type="submit" class="btn btn-outline-secondary">Edit Profile</button>
    </form>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}

{% block title %}Daily Parrot{% endblock title %}

{% block styles %}
<style>
    .avatar{
        border-radius: 100px;
    }
    .blog-entry{
        margin-bottom: 1px;
    }
    a{
        text-decoration: none;
        color: black;
    }
    a:hover{
        text-decoration: none;
        color: black;
    }
    .popular-row{
        border-bottom: 1px solid #0000001e;
    }
    .infinite-item{
        padding-bottom: 15px;
        border-bottom: 1px solid #0000001e;
    }
    #topic{
        color: #00000059;
    }
</style>
{% endblock styles %}

{% block scripts %}
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script>
    $(document).ready(function () {
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0]
        });
    });
</script>
{% endblock scripts %}

{% block content %}
    <div class="row ml-4 h-100">
        <div class="col-md-10">
            <h3>LATEST ON DAILY PARROT</h3><hr>
            <div class="infinite-container">
            {% for blog_post in posts %}
                    <div class="row blog-entry mb-4 infinite-item">
                        <a href="{% url 'blog_post' username=blog_post.author.user.username blog_post_slug=blog_post.slug %}">
                        <div class="col-md-8">
                            <p id="topic">{{ blog_post.topic|upper }}</p>
                            <h3>{{ blog_post.title }}</h3>
                            <p class="text-muted mb-0">{{ blog_post.tagline }}</p>
                            <p><a href="{% url 'profile' blog_post.author.user.username %}">
                                {{ blog_post.author.user.first_name }} 
                                {{ blog_post.author.user.last_name }}</a>
                                 &middot; 
                                <span class="text-muted">{{ blog_post.updated|date:"M j" }}</span>
                            </p>
                        </div>
                    </a>
                        <div class="col-md-2 ml-auto my-auto">
                            {% thumbnail blog_post.banner "170x159" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                            {% endthumbnail %}
                        </div>
                    </div>
                {% empty %}
                <h1>Nothing here yet...</h1>
                <a href="{% url 'blog_post_create' %}">Be the first to add</a>
            {% endfor %}
            </div>
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}" class="infinite-more-link">
                    <div class="d-flex mx-auto spinner-border"></div>
                </a>
            {% endif %}
        </div>
        <div class="col-md-2">
            {% if authors %}
            <h3>top authors</h3>
            {% for author in authors %}
                <div class="row mb-2">
                    <div class="col-auto">
                        <a href="{% url 'profile' username=author.user.username %}">
                        {% thumbnail author.avatar "40x40" crop="center" as im %}
                            <img src="{{ im.url }}" class="avatar" height="{{ im.height }}" width="{{ im.width }}">
                        {% endthumbnail %}
                        </a>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'profile' username=author.user.username %}">
                        {{ author.user.first_name }} {{ author.user.last_name }}
                        </a>
                    </div>
                    </a>
                    <hr>
                </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/topics.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Explore topics{% endblock title %}

{% block styles %}
<style>
    h1.pt-4.pb-4{
        font-weight: bold;
    }
    .col-auto{
        padding-bottom: 15px;
    }
    .card-title{
        height:70px
    }
    .card{
        width: 277.986px;
        height: 225.990px;
        margin-bottom: 25px;
    }
    .card-body{
        padding: 0px;
        width: 277.99px;
        height: 155.99px;
    }
    #topic-link{
        color: black;
        text-decoration: none;
    }
    #plus{
        font-size: 30px;
    }
    a, a:hover{
        color: black;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <h1 class="pt-4 pb-4 mb-4">Explore topics</h1>
    {% for classification in classifications %}
    {% if classification.topics.all %}
    <h2>{{ classification.name }}</h2><hr>
        <div class="row justify-content-center mb-4">
        {% for topic in classification.topics.all %}
            <div class="col-auto">
                <a id='topic-link' href="{% url 'topic' topic.slug %}">
                <div class="card">
                    <div class="card-title pt-3 pl-3 mb-0">
                        <div class="row">
                            <div class="col-auto">
                                <h4>{{ topic.name|truncatechars:"12" }}</h4>
                            </div>
                            <div class="col-auto my-auto mr-auto">
                                {% if topic in user.profile.topics.all %}
                                    <a href="{% url 'unfollow_topic' topic.slug %}" data-toggle='tooltip' data-placement='top'
                                    title="unfollow {{ topic.name }}">
                                        <span id="plus" class="fas fa-minus-circle"></span>
                                    </a>
                                {% else %}
                                    <a href="{% url 'follow_topic' topic.slug %}" data-toggle='tooltip' data-placement='top'
                                    title="follow {{ topic.name }}">
                                        <span id="plus" class="fas fa-plus-circle"></span>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% thumbnail topic.banner "278x180" crop="center" as im %}
                            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
                            alt="{{ topic.name }}">
                        {% endthumbnail %}
                    </div>
                </div>
                </a>
            </div>
        {% endfor %}
        </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock content %}